config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  require 'sidekiq/web' 
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  devise_scope :user do
      root 'devise/sessions#new'
  end

  mount CmAdmin::Engine => "/admin"
  # mount CmGraphql::Engine => "/cm-graphql"
  # mount CmCart::Engine => "/cm-cart"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  include CmAdmin::Address
end

app/models/api_key.rb
class ApiKey < ApplicationRecord
  include Auth::ApiKey
  
  belongs_to :user
  before_create :generate_access_token, :set_expiration

  scope :live, -> {where('expires_at > ?', DateTime.now)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ActiveStorage::Reflection::ActiveRecordExtensions
  ActiveRecord::Reflection.singleton_class.prepend(ActiveStorage::Reflection::ReflectionExtension)
  include ActiveStorage::Attached::Model
  
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  include CmAdmin::Assessment
  belongs_to :assessable, polymorphic: true

  scope :with_one, -> {
    where('title ILIKE ?', '%one%')
  }
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  include CmAdmin::Chapter
  belongs_to :course
  has_many :lessons

  scope :advanced, lambda {
    where('title ILIKE ?', '%advanced%')
  }
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  include CmAdmin::Coupon
  belongs_to :user

  enum status: { enabled: 0, disabled: 1 }

  def activate
    self.status = :enabled
    self.save!
  end

  def deactivate
    self.status = :disabled
    self.save!
  end
end

app/models/course.rb
class Course < ApplicationRecord
  include CmAdmin::Course

  has_action_trail

  has_many :chapters
  has_many :course_coaches
  has_many :coaches, through: :course_coaches, source: :user
  has_many :assessments, as: :assessable
  has_one :course_detail

  # monetize :price_cents

  store_accessor :meta_data, :seo_keywords

  enum level: { beginner: 0, intermediate: 1, advanced: 2 }

  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :course_coaches, reject_if: :all_blank, allow_destroy: true

  scope :only_beginner, lambda {
    where(level: :beginner)
  }
end

app/models/course_coach.rb
class CourseCoach < ApplicationRecord
  include CmAdmin::CourseCoach
  belongs_to :course
  belongs_to :user
end

app/models/course_detail.rb
class CourseDetail < ApplicationRecord
  belongs_to :course
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
  attribute :request_id, :user_agent, :ip_address

  resets { Time.zone = nil }

  def user=(user)
    super
  end
end

app/models/educational_detail.rb
class EducationalDetail < ApplicationRecord
  include CmAdmin::EducationalDetail
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  include CmAdmin::Lesson
  belongs_to :chapter
end

app/models/location.rb
class Location < ApplicationRecord
  include CmAdmin::Location

  enum location_type: { country: 0, state: 1, city: 2 }
end

app/models/log.rb
class Log < ApplicationRecord
  include CmAdmin::Log
  belongs_to :loggable, polymorphic: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  include CmAdmin::OrderItem

  belongs_to :product

  # monetize :product_price_cents
end

app/models/otp_request.rb
class OtpRequest < ApplicationRecord
  include Auth::OtpRequest

  after_commit :send_otp_email
  belongs_to :user
  enum status: [:created, :verified, :resent, :time_out, :cancelled]

  def send_otp_email
    # SendOtpEmailJob.perform_later(self.user_id)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include CmAdmin::Product

  # monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  include Auth::User
  include CmAdmin::User
  
  attr_accessor :skip_password_validation

  before_validation :skip_password, on: :create
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :api_keys
  has_many :otp_requests
  has_many :educational_details, inverse_of: :user
  accepts_nested_attributes_for :educational_details, reject_if: :all_blank, allow_destroy: true

  has_one_attached :profile_picture

  validates :first_name, length: { maximum: 10, too_long: "%{count} characters is the maximum allowed" }


  enum gender: { male: 0, female: 1 }

  def user_name
    email.split('@').first
  end

  def super_admin?
    true
  end

  protected

  def skip_password
    self.skip_password_validation = true
  end

  def password_required?
    return false if skip_password_validation
    super
  end
end

app/models/zoom_registration.rb
class ZoomRegistration < ApplicationRecord
  has_rich_text :body_text if defined? ActionText::RichText
  has_one_attached :cover_image  if defined? ActionText::RichText
  include CmAdmin::ZoomRegistration
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def components
    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_educational_detail_fields.slim
.fields-group
  .field-item
    = f.input :institution
  .field-item
    = f.input :address_line1
  .field-item
    = f.input :address_line2
  .field-remove
    = link_to_remove_association f
      i.fa.fa-times aria-hidden="true"

app/views/static_pages/_filters.html.slim
.cm-filters-v2    
  .cm-filters-v2__inner
    .filter-search 
      .form-field
        .field-input-wrapper
          input.search-input type="text" placeholder="Search"
          span.search-input-icon
            i.fa.fa-search
    .filter-chips-wrapper   
      .filter-chip
        span 
        | City is
        span 
        | Chennai +2 more
        .filter-chip-remove
          i.fa.fa-times.bolder
    .add-filter-btn 
      span +
      | Add filter
    .clear-btn 
      | Clear
      

/ .cm-filters
/   .cm-filters__lhs
/     .filter-field 
/       input.field-area type="text" placeholder="search"
/       span.fa.fa-search.search-icon
/     .filter-field 
/       select.single-select
/         option value="one"  First
/         option value="two"  Second 
/         option value="three"  Third
/     .filter-field 
/       select.single-select
/         option value="one"  First
/         option value="two"  Second 
/         option value="three"  Third
/     .filter-field 
/       select.single-select
/         option value="one"  First
/         option value="two"  Second 
/         option value="three"  Third
/     .filter-field
/       input.filter-rangepicker name="daterange" type="text"
/     .filter-field
/       select.multi-select multiple="multiple" name="states[]" data-placeholder="Multi select"
/         option value="D@"  Duke 200
/         option value="RC"  Rc 200
/         option value="D3"  Duke 390
/         option value="RC3" Rc 390
/   .cm-filters__rhs
/     button.filter-btn
/       span
/         i.fa.fa-plus
/       | ADD

app/views/static_pages/_form.html.slim
.form-wrapper
  .flag-alert.mb-4
    p.alert-header
        span
          i.fa.fa-exclamation-triangle
        | Attention
    .alert-body
      p.body-title 
        | Error heading
      p.body-info 
        | The details of the error would be explained in this line. It could also be listed out as points on below the other if there are multiple reasons.
  .form-container
    p.form-title 
      | Section heading
    .form-container__inner
      = simple_form_for(:user, url: '/users') do |f|
        = f.error_notification
        .form-field
          .field-label-wrapper
            label.field-label
              | Label
          .field-input-wrapper
            input.normal-input.error type="text" placeholder="Placeholder"
            p.error-msg
              span
                i.fa.fa-exclamation-circle
              | Error message
        .form-field.mt-3
          .field-label-wrapper
            label.field-label
              | Label
          .field-input-wrapper
            input.normal-input type="text" placeholder="Placeholder"
        .form-field.mt-3
          .field-label-wrapper
            label.field-label
              | Label
              span 
                | (Required)
          .field-input-wrapper
            input.normal-input type="text" placeholder="Placeholder"

  .form-container.mt-5
    p.form-title 
      | Section heading
    .form-container__inner
      = simple_form_for(:user, url: '/users') do |f|
        = f.error_notification
        .form-field
          .field-label-wrapper
            label.field-label
              | Label
          .field-input-wrapper
            input.normal-input.error type="text" placeholder="Placeholder"
            p.error-msg
              span
                i.fa.fa-exclamation-circle
              | Error message
        .form-field.mt-3
          .field-label-wrapper
            label.field-label
              | Label
          .field-input-wrapper
            input.normal-input type="text" placeholder="Placeholder"
        .form-field.mt-3
          .field-label-wrapper
            label.field-label
              | Label
              span 
                | (Required)
          .field-input-wrapper
            input.normal-input type="text" placeholder="Placeholder"

  button.cta-btn.mt-3 type="button" 
    | Call to action

    
    




/ Old form code
/ .custom-form
/   = simple_form_for([:admin, user]) do |f|
/     = f.error_notification
/     .form-field
/       .form-input
/         = f.input :first_name
/     .form-field
/       .form-label 
/         | Last name
/         span.required-symbol *
/       .form-input
/         input type="text" placeholder="Last name"
/       p.error-text Error message
/     .form-field
/       .form-label 
/         | Select Date
/       .form-input
/         input data-provide="datepicker" 
/     .form-field
/       .form-label 
/         | Select type
/       .form-select
/         select.single-select
/           option value="one"  First
/           option value="two"  Second 
/           option value="three"  Third
/     .form-field
/       .form-label 
/         | Upload file
/       .file-upload
/         input#img data-behaviour="upload-image" accept="image/*" name="img" type="file" 
/         span data-behaviour="upload-title" Upload
/         i.fa.fa-upload.upload-icon
/     .form-field
/       = f.simple_fields_for :educational_details do |educational_detail|
/         = render 'educational_detail_fields', f: educational_detail
/       .add-field-btn
/         = link_to_add_association '+ Add institution', f, :educational_details
/     .form-field
/       input.cm-radio#male name="gender" type="radio" value="male" 
/       label.radio-label for="male"  Male
/     .form-field
/       input.cm-checkbox#vehicle1 name="vehicle1" type="checkbox" value="Bike" /
/       label.checkbox-label for="vehicle1"  I have a bike
/     .form-actions
/       = f.button :submit

/   button.app-btn.mt-2 data-target="#exampleModal" data-toggle="modal" type="button" 
/     | Launch demo modal
  
  
  /! Modal
  #exampleModal.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
    .modal-dialog role="document" 
      .modal-content
        .modal-header
          h5#exampleModalLabel.modal-title Modal title
          button.close aria-label="Close" data-dismiss="modal" type="button" 
            span aria-hidden="true"  &times;
        .modal-body
          | Admin panel modal
        .modal-footer
          button.btn.btn-secondary data-dismiss="modal" type="button"  Close
          button.btn.btn-primary type="button"  Save changes

        

app/views/static_pages/_table.html.slim
.admin-table-index
  .table-top  
    p.table-top__total-count 104 users found
    .table-top__column-action
      button.secondary-btn.column-btn data-target="#columnActionModal" data-toggle="modal" type="button"
        span 
          i.fa.fa-columns.bolder
        span 
          i.fa.fa-angle-down
      #columnActionModal.modal.fade.table-column-modal aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
        .modal-dialog role="document" 
          .modal-content
            .modal-header
              h5#exampleModalLabel.modal-title Manage columns
              button.close aria-label="Close" data-dismiss="modal" type="button" 
                span aria-hidden="true"  &times;
            .modal-body
              .columns-list
                .column-item  
                  .column-item__name
                    p User
                  .column-item__action  
                    i.fa.fa-lock.bolder
                .column-item 
                  .column-item__name
                    .dragger 
                      i.fa.fa-bars.bolder 
                    p Email
                  .column-item__action.pointer
                    i.fa.fa-times-circle.bolder
                .column-item  
                  .column-item__name
                    .dragger 
                      i.fa.fa-bars.bolder
                    p Number
                  .column-item__action.pointer
                    i.fa.fa-times-circle.bolder
                .column-item  
                  .column-item__name
                    .dragger 
                      i.fa.fa-bars.bolder
                    p Address
                  .column-item__action.pointer
                    i.fa.fa-times-circle.bolder
                .column-item 
                  .column-item__name
                    .dragger 
                      i.fa.fa-bars.bolder 
                    p Desigination
                  .column-item__action.pointer
                    i.fa.fa-times-circle.bolder
                .column-item 
                  button.secondary-btn type="button"
                    span 
                      | Add a column
                    span 
                      i.fa.fa-angle-down
                  
            .modal-footer
              button.gray-border-btn data-dismiss="modal" type="button"  Close
              button.cta-btn type="button" Save 

.new-admin-table
  table.cm-table
    thead.cm-table__header
      tr.header-row
        th.check-box-space
          span
            input.cm-checkbox type="checkbox"
        th.name-space
          span Name
        th Email
        th Number
        th Address
        th City
        th Price (INR)
        th Status
        th country
        th College
      
    tbody.cm-table__body
      tr.body-row
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down
            .popup-card.table-export-popup.hidden  
              .popup-option
                span 
                  i.fa.fa-file-pdf-o
                | Export PDF
              .popup-option
                span 
                  i.fa.fa-file-text
                | Export CSV

      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down
      
      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down
      
      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down

      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down

      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down
      
      tr.body-row 
        td.check-box-space
          span 
            input.cm-checkbox type="checkbox"
        td Barath
        td Barath@commutatus.com
        td 8753536262
        td.text-ellipsis 57/11, Thiruvalluvar salai, Teynampet 
        td Chennai
        td 1,000
        td 
          span.status-tag.green-tag
            | STATUS GREEN
        td TamilNadu
        td Gurunanak college
        td.row-action-cell
          .row-action-tool  
            button.secondary-btn.tool-btn type="button"
              span 
                i.fa.fa-bars.bolder
              span 
                i.fa.fa-angle-down



/ .admin-table.mt-5
/   .record-found
/     | 115 companies found

/   table.cm-table
/     thead.cm-table__header
/       tr
/         th First Name
/         th Last Name
/         th Email Id
/         th Phone number
/         th Location 
/         th 
      
/     tbody.cm-table__body
/       tr 
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td 
/           img alt=("Commutatus logo") src="https://s3.ap-south-1.amazonaws.com/mentormind/companies/profile_pictures/000/000/103/original/Commutatus_logo.jpg?1557384349" width="60px"
/         td 
/           i.fa.fa-pencil.edit-icon
/       tr 
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td 
/           img alt=("Commutatus logo") src="https://s3.ap-south-1.amazonaws.com/mentormind/companies/profile_pictures/000/000/103/original/Commutatus_logo.jpg?1557384349" width="60px"
/         td 
/           i.fa.fa-pencil.edit-icon
/       tr 
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td Commutatus
/         td 
/           img alt=("Commutatus logo") src="https://s3.ap-south-1.amazonaws.com/mentormind/companies/profile_pictures/000/000/103/original/Commutatus_logo.jpg?1557384349" width="60px"
/         td 
/           i.fa.fa-pencil.edit-icon

      
.cm-pagination
  .cm-pagination__lhs Showing 1 to 15 out of 104 
  .cm-pagination__rhs 
    span.page-move-btn.disabled   
      i.fa.fa-angle-double-left.bolder.f14
    span.page-move-btn.disabled 
      i.fa.fa-chevron-left.bolder
    span.page-num-btn.active 1
    span.page-num-btn 2
    span.page-num-btn 3
    span.page-num-btn 4
    span.page-num-btn 5
    span.page-move-btn   
      i.fa.fa-chevron-right.bolder
    span.page-move-btn   
      i.fa.fa-angle-double-right.bolder.f14
    
  / cm_paginate(@filtered_result.facets)

app/views/static_pages/_tabs.html.slim
.cm-tabs-bar 
  .tab-item.active Details
  .tab-item Table 
  .tab-item Histroy 

app/views/static_pages/index.html.slim
- content_for :bread_crumb do
  p.breadcrumb-text
    = link_to  "Home ", admin_users_path
    '/
    span.active = link_to  "Users", admin_users_path

.index-page
  .index-page__filters
    == render 'filters'
  .index-page__table-container
    == render 'table'

app/views/static_pages/new.html.slim
.form-page
  .form-page__inner
    == render 'form', user: @user

/ .form-wrapper
/   .form-wrapper__top-bar
/     .back-btn
/       span
/         i.fa.fa-arrow-left aria-hidden="true"
/       | Back
/   .form-wrapper__inner
/     .paper
/       == render 'form', user: @user

app/views/static_pages/show.html.slim
.show-page
  .show-page__tabs 
    == render 'tabs'
  .show-page__inner
    .info-section
      p.section-heading   
        | Section heading
      .paper
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            span.status-tag.green-tag
              | STATUS GREEN

    .info-section
      p.section-heading   
        | Section heading
      .paper
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus
        .info-split
          .info-split__lhs
            p Name
          .info-split__rhs
            p Commutatus